### ISSUE TITLE
Redundant versioned column selects on already selected columns

### ISSUE THREAD

**Issue by safakz** [ProAI/eloquent-versioning#12]
If a model query already have any versioned columns, we can simply pass adding 'versionTable.*'

ProAI\Versioning\BuilderTrait@getModels:21

`
if (strpos(implode(',', $tempColumns), $this->model->getVersionTable().'.') === false) 
{            foreach($tempColumns as $column) {
                $segments = explode('.', $column);
                if ($segments[0] == $this->model->getTable()) {
                    $this->query->addSelect($this->model->getVersionTable().'.*');
                    break;
                }
            }
        }
  `

**Comment by crashkonijn** [comment]
Hi there @safakz,

Could you please make a PR if you'd still like to add your adjustments to this project?
